# Global metadata
title: Street Science Community
description: >
  Bring science to the public!

# Social
email: hello@streetscience.community
gitter: BackofenLab/citizen_science_group
# See: https://help.github.com/articles/repository-metadata-on-github-pages/
repository: StreetScienceCommunity/StreetScienceCommunity.github.io
participation_form: https://docs.google.com/forms/d/e/1FAIpQLScNgEDWoftccrUHXhsAOgLCFiG1FAQzQxsSW44uDTrEKwZ7_A/viewform

collections:
  events:
    permalink: /events/:path/
    output: true
  projects:
    permalink: /projects/:path/
    output: true
  protocols:
    permalink: /protocols/:path/
    output: true
